version: '3.9'
services:
  redis:
    image: 'redis/redis-stack:latest'
    ports:
      - '6379:6379'
      - '8001:8001'
    volumes:
      - redis_data:/data:rw
  server:
    build: .
    restart: on-failure
    ports:
      - '3000:3000'
    environment:
      - OPEN_WEATHER_MAP_API_KEY=your_key
      - WEATHER_STACK_API_KEY=your_key
      - REDIS_HOST=redis
      - REDIS_PORT=6379
volumes:
  redis_data:
