version: '3.9'
services:
  redis:
    image: 'redis/redis-stack-server:latest'
    ports:
      - '6379:6379'
  server:
    build: .
    restart: on-failure
    ports:
      - '3000:3000'
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
